//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsoDocApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IsoDocApp.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 سال.
        /// </summary>
        internal static string _10Year {
            get {
                return ResourceManager.GetString("10Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 سال.
        /// </summary>
        internal static string _1Year {
            get {
                return ResourceManager.GetString("1Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 سال.
        /// </summary>
        internal static string _2Year {
            get {
                return ResourceManager.GetString("2Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 ماه.
        /// </summary>
        internal static string _3Month {
            get {
                return ResourceManager.GetString("3Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 سال.
        /// </summary>
        internal static string _3Year {
            get {
                return ResourceManager.GetString("3Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 سال.
        /// </summary>
        internal static string _5Year {
            get {
                return ResourceManager.GetString("5Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 ماه.
        /// </summary>
        internal static string _6Month {
            get {
                return ResourceManager.GetString("6Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیوست فایل.
        /// </summary>
        internal static string AttachFile {
            get {
                return ResourceManager.GetString("AttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو شده.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست تغییر سند .
        /// </summary>
        internal static string ChangeDocReq {
            get {
                return ResourceManager.GetString("ChangeDocReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل شده.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فایل پیوست.
        /// </summary>
        internal static string DeleteAttachedFile {
            get {
                return ResourceManager.GetString("DeleteAttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست حذف سند .
        /// </summary>
        internal static string DeleteDocReq {
            get {
                return ResourceManager.GetString("DeleteDocReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد.
        /// </summary>
        internal static string Dep {
            get {
                return ResourceManager.GetString("Dep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالی بودن مقادیر.
        /// </summary>
        internal static string EmptyValues {
            get {
                return ResourceManager.GetString("EmptyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا سند مورد نظر خود را پیوست کنید..
        /// </summary>
        internal static string ErrorAttachFile {
            get {
                return ResourceManager.GetString("ErrorAttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در پردازش اطلاعات.
        /// </summary>
        internal static string ErrorProccessingData {
            get {
                return ResourceManager.GetString("ErrorProccessingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در پردازش اطلاعات.
        /// </summary>
        internal static string ExceptionThrown {
            get {
                return ResourceManager.GetString("ExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا همه مقادیر را وارد کنید.
        /// </summary>
        internal static string FillAllValues {
            get {
                return ResourceManager.GetString("FillAllValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال انجام.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ایجاد سند جدید.
        /// </summary>
        internal static string NewCreateDocReq {
            get {
                return ResourceManager.GetString("NewCreateDocReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب مدت زمان نگهداری سند.
        /// </summary>
        internal static string SelectDocKeepDuration {
            get {
                return ResourceManager.GetString("SelectDocKeepDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عنوان.
        /// </summary>
        internal static string WithTitle {
            get {
                return ResourceManager.GetString("WithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
